//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.MedioClinic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BasicSection.CLASS_NAME, typeof(BasicSection))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type BasicSection.
	/// </summary>
	public partial class BasicSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.BasicSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with BasicSection fields.
		/// </summary>
		private readonly BasicSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BasicSectionID.
		/// </summary>
		[DatabaseIDField]
		public int BasicSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BasicSectionID"), 0);
			}
			set
			{
				SetValue("BasicSectionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string BasicSectionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BasicSectionName"), @"");
			}
			set
			{
				SetValue("BasicSectionName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BasicSection fields.
		/// </summary>
		[RegisterProperty]
		public BasicSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BasicSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BasicSectionFields : AbstractHierarchicalObject<BasicSectionFields>
		{
			/// <summary>
			/// The content item of type BasicSection that is a target of the extended API.
			/// </summary>
			private readonly BasicSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BasicSectionFields" /> class with the specified content item of type BasicSection.
			/// </summary>
			/// <param name="instance">The content item of type BasicSection that is a target of the extended API.</param>
			public BasicSectionFields(BasicSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BasicSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BasicSectionID;
				}
				set
				{
					mInstance.BasicSectionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.BasicSectionName;
				}
				set
				{
					mInstance.BasicSectionName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BasicSection" /> class.
		/// </summary>
		public BasicSection() : base(CLASS_NAME)
		{
			mFields = new BasicSectionFields(this);
		}

		#endregion
	}
}